x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: services/airflow/Dockerfile.airflow
  env_file:
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - PYTHONPATH=/opt
  volumes:
    - ./services/airflow/dags:/opt/airflow/dags
    - ./services/airflow/logs:/opt/airflow/logs
    - ./services/airflow/plugins:/opt/airflow/plugins
    - ./schemas:/opt/schemas
    - ./project_utils:/opt/project_utils
    # W produkcji na razie nie montujemy shared (odkomentuj, gdy potrzebujesz)...
    # - shared_data:${DATA_DIR}
    # - shared_models:${MODELS_DIR}
    # - shared_config:${CONFIG_DIR}
    # ... i usuń poniższe linie, gdy nie potrzebujesz montować tych katalogów
    - ./shared/data:${DATA_DIR}
    - ./shared/models:${MODELS_DIR}
    - ./shared/config:${CONFIG_DIR}
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
  
  # Opcjonalny serwis shared (odkomentuj gdy potrzebujesz)
  # shared:
  #   build:
  #     context: ./shared
  #     dockerfile: Dockerfile.shared
  #   volumes:
  #     - shared_data:/shared/data
  #     - shared_models:/shared/models
  #     - shared_config:/shared/config

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    
  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow users create \
        --username admin \
        --password admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com || true"

  # Opcjonalny serwis prediction (odkomentuj gdy zrobisz działający develop i UI)
  # prediction-service:
  #   build:
  #     context: .
  #     dockerfile: prediction_service/Dockerfile
  #   env_file: 
  #     - .env
  #   environment:
  #     - DATA_DIR=/opt/shared/data
  #     - MODELS_DIR=/opt/shared/models
  #     - CONFIG_DIR=/opt/shared/config
  #   volumes:
  #     - ./prediction_service/app:/opt/app/
  #     - ./shared/data:${DATA_DIR}
  #     - ./shared/models:${MODELS_DIR}
  #     - ./shared/config:${CONFIG_DIR}
  #   ports:
  #     - '${SERVICE_PORT}:8000'
  #   depends_on:
  #     - airflow-webserver

volumes:
  postgres_data:
  # shared_data:
  # shared_models:
  # shared_config: